name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        git rm -r $GITHUB_WORKSPACE/*.bin || true
    - name: Run PlatformIO main esp8266_2m
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/Aircoookie/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/mm.zip
        unzip -o /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -name "WLED-*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp8266_2m' >>platformio.ini
        echo 'build_flags = ${env:esp8266_2m.build_flags} -D USERMOD_AUTO_SAVE -D USERMOD_BME280 -D USERMOD_PWM_FAN -D USERMOD_DALLASTEMPERATURE -D USERMOD_PWM_OUTPUTS' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp8266_2m.lib_deps}' >>platformio.ini
        echo '  BME280@~3.0.0' >>platformio.ini
        echo '  Wire' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build || true
    - name: Copy Files main esp8266_2m
      run: |
        cd $GITHUB_WORKSPACE
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/build_main_esp8266_2m.bin || true
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files main esp8266_2m
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/build_main_esp8266_2m.bin || true
        git add $GITHUB_WORKSPACE/last_update_date.txt || true
        git commit -m "Commit Custom Build" || true
        git push origin main || true
